blog_homepage:
    path:     /
    defaults: { _controller: FnKBlogBundle:Post:list }

blog_post_new:
    path:     /post/new
    defaults: { _controller: FnKBlogBundle:Post:new }

blog_category_new:
    path:     /category/new
    defaults: { _controller: FnKBlogBundle:Category:new }